version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - my-datavolume:/data
    networks:
      - backend

volumes:
  my-datavolume:

networks:
  backend: